# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: WAR build

on:
  push:
    branches: [ feature/war, feature/jakarta-upgrade, master, feature/*, dev ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build war with Maven
        run: mvn compile war:war
      - name: Archive war
        uses: actions/upload-artifact@v2
        with:
          name: controlserver-war
          path: target/rtr-*.war
          retention-days: 365
